<#
.SYNOPSIS
    Shared YAML helpers for the documentation homepage.

.DESCRIPTION
    Dot-sourced, not invoked: this file defines functions and does nothing else,
    so sourcing it has no side effects.

    Two callers need identical escaping and must not be free to drift apart:

      ConvertTo-DocumentationHomepage.ps1  the real homepage, generated from a
                                           README, and re-generated by the gate's
                                           drift check and the preview script
      setup-docs.ps1                       the stub homepage written when a
                                           project has no README

    Those two paths are mutually exclusive for any one project, so a divergence
    could not corrupt a single site -- but it would silently escape front matter
    differently between projects, which is exactly the kind of second
    implementation this template avoids elsewhere.

    Installed alongside the generator into the project's script directory, so the
    installed generator can source it at run time.
#>

function ConvertTo-YamlSingleQuotedScalar {
    <#
    .SYNOPSIS
    Serializes a string as a single-line, single-quoted YAML scalar.

    Front matter fields here are single-line browser-tab and meta-description
    text, so an embedded newline is collapsed to a space rather than kept --
    keeping it would either break the YAML block or require a block-scalar style
    this front matter does not otherwise use, and either way a raw newline is
    exactly what lets a value close the front matter early and inject fabricated
    keys after it. Embedded single quotes are doubled, which is single-quoted
    YAML's own escape and cannot reopen the block either.
    #>
    param (
        [Parameter(Mandatory)]
        [AllowEmptyString()]
        [string] $Value
    )

    $collapsed = ($Value -replace '\r\n?|\n', ' ').Trim()
    return "'$($collapsed.Replace("'", "''"))'"
}
